### ISSUE TITLE
Epic: Setup Viper and Trace

### ISSUE THREAD

**Issue by non-binary** [bitrise-io/bumblebee#18]
### Description: 

This epic is dedicated to creating the Viper modules for Bumblebee and integrating Sparkle and Trace into the project.

#### Corresponding Issues

- [x] Setup Trace SDK => #21. Implemented in #21.
- [x] ~~Setup Sparkle SDK => #20.~~ This is blocked until at least Q1 2021. See #27.
- [x] Create Viper modules => #19.

### Implemented in: 

This will be implemented in Swift in the Mac application.
