### ISSUE TITLE
Initial milestone

### ISSUE THREAD

**Issue by non-binary** [bitrise-io/bumblebee#19]
This initial milestone will focus on setting the ground work for the project including planning and scaffolding.

- [x] Implement starter project for `bumblebee-mac`.
- [x] Implement starter project for `bumblebee-slack`.
- [ ] Plan out the 2.0 release.
- [ ] Create all GitHub issues for 2.0 release tasks.
- [ ] Implement starter project for `bumblebee-backend`.
- [ ] Implement Slack integration #29.
- [ ] Implement #18 (deep-links).
- [ ] Implement #7 (SSO).
