### ISSUE TITLE
Task: Create starter projects

### ISSUE THREAD

**Issue by non-binary** [bitrise-io/bumblebee#5]
### Description: 

Create the starter/empty projects.

- [x] Create Mac project => #13.
- [x] Create Slack project => #14.
- [x] Create Backend project => #15.

### Implemented in: 

The Mac project will be in Swift, the Slack project in Rust and the backend project in Rust.
