### ISSUE TITLE
Epic: Getting Started

### ISSUE THREAD

**Issue by non-binary** [bitrise-io/bumblebee#7]
### Description: 

The tasks involved in getting started with the development of Bumblebee v2.

#### Corresponding Issues

- [x] Choose UI framework => #3. **UIKit**!
- [x] Choose architecture => #4. **Viper**!
- [x] Create starter projects => #5.
- [x] Create Bitrise projects and their workflows => #6.

### Implemented in: 

This is more of a planning epic however there are some implementations in Swift and Rust in their respective components (Mac, Slack, Backend).
